#!/bin/bash

for (( rs = 1; rs < 4; rs++ )); do
  echo "Intializing replica ${rs} set"
  replicate="rs.initiate(); sleep(1000); rs.add(\"mongors${rs}n2\"); rs.add(\"mongors${rs}n3\"); cfg=rs.conf(); cfg.members[0][\"host\"] = \"mongors${rs}n1\"; rs.reconfig(cfg); rs.status();"
  echo ${replicate}
  docker exec -it mongodockercompose_mongors${rs}n1_1 bash -c "echo '${replicate}' | mongo"
done

sleep 1
# Add better mechanisum to wait for mongos connectivity to be
# established by tailing docker log for connection readiness

rs1=$(docker ps -a | grep mongors1n1 | cut -d' ' -f1)
rs2=$(docker ps -a | grep mongors2n1 | cut -d' ' -f1)
docker exec -it mongodockercompose_mongos1_1 bash -c "echo \"sh.addShard('mongors1/mongors1n1:27017'); sh.addShard('mongors2/mongors2n1:27017');\" | mongo "
