#!/bin/bash

for (( rs = 1; rs < 3; rs++ )); do
  echo "Intializing replica ${rs} set"
  replicate="rs.initiate(); rs.add(\"mongors${rs}n2\"); rs.add(\"mongors${rs}n3\"); sleep(1000); rs.status();"
  docker exec -it mongodockercompose_mongors${rs}n1_1 bash -c "echo '${replicate}' | mongo"
done

sleep 1
# Add better mechanisum to wait for mongos connectivity to be
# established by tailing docker log for connection readiness

rs1=$(docker ps -a | grep mongors1n1 | cut -d' ' -f1)
rs2=$(docker ps -a | grep mongors2n1 | cut -d' ' -f1)
docker exec -it mongodockercompose_mongos1_1 bash -c "echo \"sh.addShard('mongors1/${rs1}:27017'); sh.addShard('mongors2/${rs2}:27017');\" | mongo "
